updated workflows

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -293,11 +293,18 @@ jobs:
 
       - name: Terraform Apply
         run: |
-          echo "Starting Terraform Apply..."
-          terraform apply -parallelism=${{ inputs.parallelism }} -auto-approve -no-color ${{ github.event.repository.name }}-${{ inputs.environment }}.out
-          if [[ $? -ne 0 ]]; then
-            echo "Terraform Apply Failed!"
+          output=$(mktemp)
+          terraform apply -auto-approve -no-color ${{ github.event.repository.name }}.out 2>&1 | tee "output"
+          if [[ ${PIPESTATUS[0]} -ne 0]]; then
+            echo "#### Terraform Apply Failed" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            cat "$output" >> $GITHUB_STEP_SUMMARY
+            ECHO '```' >> $GITHUB_STEP_SUMMARY
             exit 1
+          else
+            echo "#### Terraform apply succeeded" >> $GITHUB_STEP_SUMMARY
+            echo "Release Hash: $(echo '${{ github.sha }}') | cut -c1-7)" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            cat "$output" >> $GITHUB_STEP_SUMMARY
+            ECHO '```' >> $GITHUB_STEP_SUMMARY
           fi
-          echo "Terraform Apply Succeeded!"
-        shell: /usr/bin/bash -e {0}
