updated workflows

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -16,7 +16,7 @@ on:
         type: string
         required: true
         description: "What AWS env to deploy to"
-        default: "none"
+        default: "prd"
       parallelism:
         type: string
         required: false
@@ -26,12 +26,17 @@ on:
         type: string
         required: false
         description: "What S3 bucket to use for terraform state files"
-        default: "none"
+        default: "395101865577-terraform-state-bucket"
+      state_bucket_path:
+        type: string
+        required: false
+        description: "The path to the state file"
+        default: "core/terraform.tfstate"
       state_bucket_region:
         type: string
         required: false
         description: "What region the state bucket is in"
-        default: "cpe-control-repo-platform-ets-app-workloads-master-eu-west-1"
+        default: "eu-west-2"
       terraform_version:
         type: string
         required: false
@@ -40,7 +45,13 @@ on:
 
 env:
   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
-  SSH_KEY: ${{ secrets.GH_ACTIONS_SERVICE_USER_SSH_KEY }} #
+  SSH_KEY: ${{ secrets.GH_ACTIONS_SERVICE_USER_SSH_KEY }}
+  AWS_DEFAULT_REGION: eu-west-2
+  AWS_REGION: eu-west-2
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
+  tfvars_path: ./env/prd.tfvars
 
 jobs:
   plan:
@@ -50,38 +61,14 @@ jobs:
       id-token: write
       contents: write
     steps:
-      # Check if on default branch
-      - name: Check if on default branch
-        if: github.ref_name != github.event.repository.default_branch
-        run: |
-          job_summary="### Job failed :warning:\nThis workflow is intended to run only on the default branch (${{ github.event.repository.default_branch }}). Exiting because it is running on branch ${{ github.ref_name }}."
-          echo -e "$job_summary" >> $GITHUB_STEP_SUMMARY
-          exit 1
+      - name: Check out repo
+        uses: actions/checkout@v4
 
-      # Cache Terraform modules and providers
-      - name: Cache Terraform Modules
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.terraform.d/plugin-cache
-            .terraform
-          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
-          restore-keys: |
-            ${{ runner.os }}-terraform-
-
-      # Check out repo
-      - uses: actions/checkout@v4
-      
-      # Set up terraform
-      - uses: hashicorp/setup-terraform@v3
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: ${{ inputs.terraform_version }}
 
-      # Terraform Validate
-      - name: Terraform Validate
-        run: terraform validate
-
-      # Load environment configurations
       - name: Load environment-specific configuration
         id: load_config
         uses: actions/github-script@v7
@@ -93,7 +80,6 @@ jobs:
             const defaults = {
               aws_region: "${{ inputs.aws_region }}",
               code_owner: "${{ inputs.code_owner }}",
-              parallelism: "${{ inputs.parallelism }}",
               state_bucket: "${{ inputs.state_bucket }}",
               state_bucket_region: "${{ inputs.state_bucket_region }}"
             };
@@ -105,11 +91,11 @@ jobs:
               } else if (!fullConfig[environment].role_to_assume) {
                 core.setFailed(`'role_to_assume' is not defined in the configuration for the given environment '${environment}'.`);
               } else {
-                config = { ...defaults, ...fullConfig[environment] }; // Merge defaults with environment-specific config
+                config = { ...defaults, ...fullConfig[environment] };
               }
             } else {
               core.setFailed(`Configuration file not found at '${configPath}'`);
-            } 
+            }
             for (const key in config) {
               if (config[key]) {
                 core.setOutput(key, config[key]);
@@ -117,7 +103,6 @@ jobs:
               }
             }
 
-      # Authenticate via OIDC to AWS
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -125,7 +110,6 @@ jobs:
           role-to-assume: ${{ steps.load_config.outputs.role_to_assume }}
           role-session-name: GithubActionsSession
 
-      # Check if .tfvars file exists
       - name: Check Environment Configuration
         id: check_env
         run: |
@@ -133,40 +117,44 @@ jobs:
           ENV_FILE="./env/$ENVIRONMENT.tfvars"
           if [[ "$ENVIRONMENT" != "none" ]] && [ ! -f "$ENV_FILE" ]; then
             echo "Error: .tfvars file does not exist for the specified environment $ENVIRONMENT."
-            job_summary="### Job Failed :warning:\n**Error:** The required .tfvars file for the environment '$ENVIRONMENT' does not exist. Please ensure the file is present in the './env/' directory and try again."
-            echo "$job_summary" >> $GITHUB_STEP_SUMMARY
-            exit 1 # Fail the step if the .tfvars file does not exist
+            echo "### Job Failed :warning:\n**Error:** The required .tfvars file for the environment '$ENVIRONMENT' does not exist. Please ensure the file is present in the './env/' directory and try again." >> $GITHUB_STEP_SUMMARY
+            exit 1
           elif [[ "$ENVIRONMENT" != "NONE" ]]; then
             echo "tfvars_path=$ENV_FILE" >> $GITHUB_ENV
           else
             echo "tfvars_path=" >> $GITHUB_ENV
           fi
 
-      # Add SSH key to allow us to clone
-      - name: Set up SSH Private Key
+      - name: Set up SSH private key
         run: |
           mkdir -p /home/runner/.ssh
           ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
-          echo "${{ env.SSH_KEY }}" > /home/runner/.ssh/github_actions
+          echo "${{ env.SSH_KEY }}" | tr -d '\r' > /home/runner/.ssh/github_actions
           chmod 600 /home/runner/.ssh/github_actions
-          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
-          ssh-add /home/runner/.ssh/github_actions
+          eval $(ssh-agent -s)
+          ssh-add /home/runner/.ssh/github_actions        
 
-      # Initialise Terraform in path
       - name: Terraform Init
         run: |
+          # Extract values from environment or configuration
           ACCOUNT_ID=$(echo "${{ steps.load_config.outputs.role_to_assume }}" | cut -d':' -f5)
-          AWS_TF_STATE_PATH=$(echo "${{ steps.load_config.outputs.code_owner }}/aws/terraform/${{ github.event.repository.name }}/$ACCOUNT_ID/${{ inputs.environment }}/terraform.tfstate" | tr '[:upper:]' '[:lower:]')
+          AWS_TF_STATE_PATH="${{ inputs.state_bucket_path }}" # Ensure this is correct and not empty
+          
+          # Ensure the path variable is not empty
+          if [ -z "$AWS_TF_STATE_PATH" ]; then
+            echo "Error: AWS_TF_STATE_PATH is empty. Please check your state_bucket_path configuration."
+            exit 1
+          fi
+          
+          # Initialize Terraform
           terraform init \
             -backend-config "bucket=${{ steps.load_config.outputs.state_bucket }}" \
             -backend-config "region=${{ steps.load_config.outputs.state_bucket_region }}" \
             -backend-config "key=$AWS_TF_STATE_PATH" \
-            -backend-config "encrypt=true"
-    
-      # Run Terraform plan   
+            -backend-config "encrypt=true"        
+
       - name: Terraform Plan
         run: |
-
           TFCMD="terraform plan -out ${{ github.event.repository.name }}-${{ inputs.environment }}.out"
           if [ -n "${{ env.tfvars_path }}" ]; then
             TFCMD="$TFCMD -var-file=${{ env.tfvars_path }}"
@@ -174,7 +162,6 @@ jobs:
           echo "Running: $TFCMD"
           eval $TFCMD
 
-      # Display Terraform Plan as markdown and append to job summary
       - name: Terraform Plan and Markdown Summary
         id: plan
         run: |
@@ -183,17 +170,17 @@ jobs:
           terraform show -no-color ${{ github.event.repository.name }}-${{ inputs.environment }}.out | tee -a $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
 
-      # Upload Terraform Plan to Artifacts
       - name: Upload Plan Artifact
         uses: actions/upload-artifact@v4
-        with: 
+        with:
           name: ${{ github.event.repository.name }}-${{ inputs.environment }}
           path: ./${{ github.event.repository.name }}-${{ inputs.environment }}.out
-    
+
       - name: Convert Terraform Plan to JSON
         id: convert_plan
         run: |
           terraform show -json ${{ github.event.repository.name }}-${{ inputs.environment }}.out | tee ${{ github.event.repository.name }}-${{ inputs.environment }}.json
+
 
   apply:
     name: Terraform Apply
