adding progress

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -39,7 +39,7 @@ on:
         default: "~1.6.0"
 
 env:
-  SSH_AUTH_SOCK: /temp/ssh_agent.sock
+  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
   SSH_KEY: ${{ secrets.GH_ACTIONS_SERVICE_USER_SSH_KEY }}
 
 jobs:
@@ -50,12 +50,24 @@ jobs:
       id-token: write
       contents: write
     steps:
+      # Check if on default branch
       - name: Check if on default branch
         if: github.ref_name != github.event.repository.default_branch
         run: |
           job_summary="### Job failed :warning:\nThis workflow is intended to run only on the default branch (${{ github.event.repository.default_branch }}). Exiting because it is running on branch ${{ github.ref_name }}."
           echo -e "$job_summary" >> $GITHUB_STEP_SUMMARY
           exit 1
+
+      # Cache Terraform modules and providers
+      - name: Cache Terraform Modules
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.terraform.d/plugin-cache
+            .terraform
+          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
+          restore-keys: |
+            ${{ runner.os }}-terraform-
 
       # Check out repo
       - uses: actions/checkout@v4
@@ -64,7 +76,11 @@ jobs:
       - uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: ${{ inputs.terraform_version }}
-      
+
+      # Terraform Validate
+      - name: Terraform Validate
+        run: terraform validate
+
       # Load environment configurations
       - name: Load environment-specific configuration
         id: load_config
@@ -150,6 +166,7 @@ jobs:
       # Run Terraform plan   
       - name: Terraform Plan
         run: |
+
           TFCMD="terraform plan -out ${{ github.event.repository.name }}-${{ inputs.environment }}.out"
           if [ -n "${{ env.tfvars_path }}" ]; then
             TFCMD="$TFCMD -var-file=${{ env.tfvars_path }}"
@@ -188,6 +205,16 @@ jobs:
     needs: plan
     environment: manual_approval
     steps:
+      # Cache Terraform modules and providers
+      - name: Cache Terraform Modules
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.terraform.d/plugin-cache
+            .terraform
+          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
+          restore-keys: |
+            ${{ runner.os }}-terraform-
 
       # Check out repo
       - uses: actions/checkout@v4
@@ -244,12 +271,18 @@ jobs:
       # Add SSH key to allow us to clone
       - name: Set up SSH Private Key
         run: |
-            mkdir -p /home/runner/.ssh
-            ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
-            echo "${{ env.SSH_KEY }}" > /home/runner/.ssh/github_actions
-            chmod 600 /home/runner/.ssh/github_actions
-            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
-            ssh-add /home/runner/.ssh/github_actions
+          mkdir -p /home/runner/.ssh
+          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
+          echo "${{ env.SSH_KEY }}" > /home/runner/.ssh/github_actions
+          chmod 600 /home/runner/.ssh/github_actions
+          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
+          ssh-add /home/runner/.ssh/github_actions
+
+      # Download Terraform Plan from Artifact
+      - name: Download Plan Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ github.event.repository.name }}-${{ inputs.environment }}
 
       # Initialise Terraform in path
       - name: Terraform Init
@@ -262,27 +295,13 @@ jobs:
             -backend-config "key=$AWS_TF_STATE_PATH" \
             -backend-config "encrypt=true"
 
-       # Download Terraform Plan output
-       - name: Download Terraform Plan output
-         uses: actions/downoad-artifact@v4
-         with: 
-            name: ${{ github.event.repository.name }}-${{ inputs.environment }}
-
-       # Run Terraform Apply and Capture output
-       - name: Terraform Apply
-         run: |
-           output=$(mktemp)
-           terraform apply -auto-approve -no-color ${{ github.event.repository.name }}.out 2>&1 | tee "output"
-           if [[ ${PIPESTATUS[0]} -ne 0]]; then
-             echo "#### Terraform Apply Failed" >> $GITHUB_STEP_SUMMARY
-             echo '```' >> $GITHUB_STEP_SUMMARY
-             cat "$output" >> $GITHUB_STEP_SUMMARY
-             ECHO '```' >> $GITHUB_STEP_SUMMARY
-             exit 1
-           else
-             echo "#### Terraform apply succeeded" >> $GITHUB_STEP_SUMMARY
-             echo "Release Hash: $(echo '${{ github.sha }}') | cut -c1-7)" >> $GITHUB_STEP_SUMMARY
-             echo '```' >> $GITHUB_STEP_SUMMARY
-             cat "$output" >> $GITHUB_STEP_SUMMARY
-             ECHO '```' >> $GITHUB_STEP_SUMMARY
-           fi
+      # Run Terraform Apply
+      - name: Terraform Apply
+        run: |
+          echo "Starting Terraform Apply..."
+          terraform apply -parallelism=${{ inputs.parallelism }} -auto-approve -no-color ${{ github.event.repository.name }}-${{ inputs.environment }}.out
+          if [[ $? -ne 0 ]]; then
+            echo "Terraform Apply Failed!"
+            exit 1
+          fi
+          echo "Terraform Apply Succeeded!"
diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -1,4 +1,4 @@
-name: "Terraform Plan"
+name: Terraform Plan
 
 on:
   workflow_call:
@@ -33,7 +33,7 @@ on:
         default: "~1.6.0"
 
 env:
-  SSH_AUTH_SOCK: /temp/ssh_agent.sock
+  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
   SSH_KEY: ${{ secrets.GH_ACTIONS_SERVICE_USER_SSH_KEY }}
 
 jobs:
@@ -44,15 +44,14 @@ jobs:
       id-token: write
       contents: write
     steps:
-      # Check out repo
-      - uses: actions/checkout@v4
-      
-      # Set up terraform
-      - uses: hashicorp/setup-terraform@v3
+      - name: Check out repo
+        uses: actions/checkout@v4
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: ${{ inputs.terraform_version }}
-      
-      # Load environment configurations
+
       - name: Load environment-specific configuration
         id: load_config
         uses: actions/github-script@v7
@@ -75,11 +74,11 @@ jobs:
               } else if (!fullConfig[environment].role_to_assume) {
                 core.setFailed(`'role_to_assume' is not defined in the configuration for the given environment '${environment}'.`);
               } else {
-                config = { ...defaults, ...fullConfig[environment] }; // Merge defaults with environment-specific config
+                config = { ...defaults, ...fullConfig[environment] };
               }
             } else {
               core.setFailed(`Configuration file not found at '${configPath}'`);
-            } 
+            }
             for (const key in config) {
               if (config[key]) {
                 core.setOutput(key, config[key]);
@@ -87,7 +86,6 @@ jobs:
               }
             }
 
-      # Authenticate via OIDC to AWS
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -95,8 +93,6 @@ jobs:
           role-to-assume: ${{ steps.load_config.outputs.role_to_assume }}
           role-session-name: GithubActionsSession
 
-
-      # Check if .tfvars file exists
       - name: Check Environment Configuration
         id: check_env
         run: |
@@ -104,16 +100,14 @@ jobs:
           ENV_FILE="./env/$ENVIRONMENT.tfvars"
           if [[ "$ENVIRONMENT" != "none" ]] && [ ! -f "$ENV_FILE" ]; then
             echo "Error: .tfvars file does not exist for the specified environment $ENVIRONMENT."
-            job_summary="### Job Failed :warning:\n**Error:** The required .tfvars file for the environment '$ENVIRONMENT' does not exist. Please ensure the file is present in the './env/' directory and try again."
-            echo "$job_summary" >> $GITHUB_STEP_SUMMARY
-            exit 1 # Fail the step if the .tfvars file does not exist
+            echo "### Job Failed :warning:\n**Error:** The required .tfvars file for the environment '$ENVIRONMENT' does not exist. Please ensure the file is present in the './env/' directory and try again." >> $GITHUB_STEP_SUMMARY
+            exit 1
           elif [[ "$ENVIRONMENT" != "NONE" ]]; then
             echo "tfvars_path=$ENV_FILE" >> $GITHUB_ENV
           else
             echo "tfvars_path=" >> $GITHUB_ENV
           fi
 
-      # Add SSH key to allow us to clone
       - name: Set up SSH Private Key
         run: |
           mkdir -p /home/runner/.ssh
@@ -123,7 +117,6 @@ jobs:
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null
           ssh-add /home/runner/.ssh/github_actions
 
-      # Initialise Terraform in path
       - name: Terraform Init
         run: |
           ACCOUNT_ID=$(echo "${{ steps.load_config.outputs.role_to_assume }}" | cut -d':' -f5)
@@ -134,7 +127,6 @@ jobs:
             -backend-config "key=$AWS_TF_STATE_PATH" \
             -backend-config "encrypt=true"
 
-      # Run Terraform plan   
       - name: Terraform Plan
         run: |
           TFCMD="terraform plan -out ${{ github.event.repository.name }}-${{ inputs.environment }}.out"
@@ -144,7 +136,6 @@ jobs:
           echo "Running: $TFCMD"
           eval $TFCMD
 
-      # Display Terraform Plan as markdown and append to job summary
       - name: Terraform Plan and Markdown Summary
         id: plan
         run: |
@@ -153,48 +144,44 @@ jobs:
           terraform show -no-color ${{ github.event.repository.name }}-${{ inputs.environment }}.out | tee -a $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
 
-      # Upload Terraform Plan to Artifacts
       - name: Upload Plan Artifact
         uses: actions/upload-artifact@v4
-        with: 
+        with:
           name: ${{ github.event.repository.name }}-${{ inputs.environment }}
           path: ./${{ github.event.repository.name }}-${{ inputs.environment }}.out
-    
+
       - name: Convert Terraform Plan to JSON
         id: convert_plan
         run: |
           terraform show -json ${{ github.event.repository.name }}-${{ inputs.environment }}.out | tee ${{ github.event.repository.name }}-${{ inputs.environment }}.json
 
-      # Scan taerraform plan with ICS Mimics
-      - name: Upload Scan Artifacts
-        uses: rapid7/insightcloudsec-actions@v2
-        continue-on-error: true
-        id: ics_scan
-        with: 
-          api_key: ${{ secrets.RAPID7_API_KEY }}
-          base_url: ${{ secrets.RAPID7_BASE_URL }}
-          config_name: IaC Analyzer - Global Use
-          target: ${{ github.event.repository.name }}-${{ inputs.environment }}.json
+      # Uncomment these steps if needed
+      # - name: Upload Scan Artifacts
+      #   uses: rapid7/insightcloudsec-actions@v2
+      #   continue-on-error: true
+      #   id: ics_scan
+      #   with:
+      #     api_key: ${{ secrets.RAPID7_API_KEY }}
+      #     base_url: ${{ secrets.RAPID7_BASE_URL }}
+      #     config_name: IaC Analyzer - Global Use
+      #     target: ${{ github.event.repository.name }}-${{ inputs.environment }}.json
 
-      # Upload scan artifact
-      - name: Upload scan artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: mimics-scan-artifacts
-          path: |
-            ./log/mimics*.log
-            ./ics_scan.*
+      # - name: Upload scan artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: mimics-scan-artifacts
+      #     path: |
+      #       ./log/mimics*.log
+      #       ./ics_scan.*
 
-      # Extract ICS scan results
-      - name: Extract Report from SARIF
-        id: extract_report
-        run: |
-          jq '.runs[] | .results' ics_scan.sarif > ics_scan.json
+      # - name: Extract Report from SARIF
+      #   id: extract_report
+      #   run: |
+      #     jq '.runs[] | .results' ics_scan.sarif > ics_scan.json
 
-      # Append ICS scan results to job summary
-      - name: Append ICS Scan Results to Job Summary
-        run: |
-          echo '```json' >> $GITHUB_STEP_SUMMARY
-          echo '### ICS Scan Results' >> $GITHUB_STEP_SUMMARY
-          cat ./ics_scan.json >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
+      # - name: Append ICS Scan Results to Job Summary
+      #   run: |
+      #     echo '```json' >> $GITHUB_STEP_SUMMARY
+      #     echo '### ICS Scan Results' >> $GITHUB_STEP_SUMMARY
+      #     cat ./ics_scan.json >> $GITHUB_STEP_SUMMARY
+      #     echo '```' >> $GITHUB_STEP_SUMMARY
